### ISSUE TITLE
drift correction fails in 2D

### ISSUE THREAD

**Issue by cleterrier** [ZhuangLab/storm-analysis#36]
I tested 3D-DAOSTORM in 2D and there was a failure at the end of the fitting, when doing drift correction. I used an xml file derived from test_3d_2d.xml, setting the drift correction to "1". The error complains "Cannot do z drift correction without 'z' position information. Set 'z_correction' parameter to 0." but there is no such parameter in the xml file?

Drift Correction.
Traceback (most recent call last):
  File "/Users/christo/Travail/Labo/Processing/Python/storm-analysis/storm_analysis/daostorm_3d/mufit_analysis.py", line 63, in <module>
    analyze(args.movie, args.mlist, args.settings)
  File "/Users/christo/Travail/Labo/Processing/Python/storm-analysis/storm_analysis/daostorm_3d/mufit_analysis.py", line 45, in analyze
    parameters)
  File "/Users/christo/anaconda3/envs/storm-analysis/lib/python3.5/site-packages/storm_analysis-2.1-py3.5.egg/storm_analysis/sa_utilities/std_analysis.py", line 124, in standardAnalysis
    parameters)
  File "/Users/christo/anaconda3/envs/storm-analysis/lib/python3.5/site-packages/storm_analysis-2.1-py3.5.egg/storm_analysis/sa_utilities/std_analysis.py", line 152, in trackDriftCorrect
    driftCorrection(h5_name, parameters)
  File "/Users/christo/anaconda3/envs/storm-analysis/lib/python3.5/site-packages/storm_analysis-2.1-py3.5.egg/storm_analysis/sa_utilities/std_analysis.py", line 63, in driftCorrection
    z_correct)
  File "/Users/christo/anaconda3/envs/storm-analysis/lib/python3.5/site-packages/storm_analysis-2.1-py3.5.egg/storm_analysis/sa_utilities/xyz_drift_correction.py", line 42, in xyzDriftCorrection
    assert h5_dc.hasLocalizationsField("z"), "Cannot do z drift correction without 'z' position information. Set 'z_correction' parameter to 0."
AssertionError: Cannot do z drift correction without 'z' position information. Set 'z_correction' parameter to 0.

**Comment by HazenBabcock** [comment]
No problem.
`<z_correction type="int">0</z_correction>`
The default behavior is to do z drift correction, so if you don't want to or can't then you have to explicitly specify.
